### ISSUE TITLE
review Request 1 BLD requests

### ISSUE THREAD

**Issue by dckc** [Agoric/validator-profiles#80]
_applicants, see [Request 1 BLD](https://github.com/Agoric/validator-profiles/wiki/Request-1-BLD)_

Hello validators!

For the purpose of decentralization, we'd like to grant 1 BLD to folks who apply in good faith. We'd like to delegate this to a group of approximately 7 of the validators who are receiving BLD delegation from Agoric in return for a pledge of support of community growth activities.

We have a discord channel for coordination: [#validator-1-bld](https://discord.com/channels/585576150827532298/946137891023777802).

We would like you to vet that the applicant
1. actually has a node running and
2. is distinct from everyone already running a validator. 

Please use github reactions and/or comments to volunteer to serve in this capacity.

cc @jeetraut @michaelfig 

## road not taken: multi-sig

~~We would supply you with, say, 50 BLD to start. You could perhaps disperse it using a 2-of-7 multi-sig cosmos account (or 3-of-7?)~~

## road not taken: knack form

We had sketched a form... https://validateagoric.knack.com/agoric-dev#validator-1-bld-program

**Comment by dckc** [comment]
Based on your pledges, I nominate @clawmvp (#16 01node) , @iicc1 (#25 Stakely.io), @Gotogu (#3 wave), @alexandruast (#60 stake.systems), @johndoe24873 (#15 johndoe), @hyehan (#79 Blockapsis), and @paddyson79 (#58 pathrocknetwork) .

Please use github reactions and/or comments to offer to serve in this capacity. Or follow up in [Agoric discord](https://agoric.com/discord).

**Comment by nodestake** [comment]
Sounds good.
Looking forward the agoric more decentralization.

**Comment by paddyson79** [comment]
This is a great idea. I'm in. Will go through the form later.

**Comment by jeetraut** [comment]
Hai Tran Thanh - TC Network - Node ID: 462aa5d3568bba44d167865825d65f7f947b337a - wallet address: agoric188xyq72fveuuvgk7lkht964jhgtc2cw0l86r7j

BINBIN WU - NodeStake.top - Node ID: 3c94a2a7e90aa98fc7f01fa96b22b6d9721dc285 - wallet address: agoric1nkhsz0uk0d8qd4p7unrwej0j3ne8acpk447cvf

**Comment by paddyson79** [comment]
Hai Tran Thanh - TC Network - Node ID: 462aa5d3568bba44d167865825d65f7f947b337a - wallet address: agoric188xyq72fveuuvgk7lkht964jhgtc2cw0l86r7j is running https://agoric.bigdipper.live/validators/agoricvaloper188xyq72fveuuvgk7lkht964jhgtc2cw00lf2zn

BINBIN WU - NodeStake.top - Node ID: 3c94a2a7e90aa98fc7f01fa96b22b6d9721dc285 - wallet address: agoric1nkhsz0uk0d8qd4p7unrwej0j3ne8acpk447cvf is not

**Comment by paddyson79** [comment]
> Hai Tran Thanh - TC Network - Node ID: 462aa5d3568bba44d167865825d65f7f947b337a - wallet address: agoric188xyq72fveuuvgk7lkht964jhgtc2cw0l86r7j
> 
> BINBIN WU - NodeStake.top - Node ID: 3c94a2a7e90aa98fc7f01fa96b22b6d9721dc285 - wallet address: agoric1nkhsz0uk0d8qd4p7unrwej0j3ne8acpk447cvf

Hai Tran Thanh - TC Network - Node ID: 462aa5d3568bba44d167865825d65f7f947b337a - wallet address: agoric188xyq72fveuuvgk7lkht964jhgtc2cw0l86r7j is running https://agoric.bigdipper.live/validators/agoricvaloper188xyq72fveuuvgk7lkht964jhgtc2cw00lf2zn

BINBIN WU - NodeStake.top - Node ID: 3c94a2a7e90aa98fc7f01fa96b22b6d9721dc285 - wallet address: agoric1nkhsz0uk0d8qd4p7unrwej0j3ne8acpk447cvf is not

**Comment by dckc** [comment]
@jeetraut where did that info about TC Network, NodeStake.top come from? Did you get those from [the knack form](https://validateagoric.knack.com/agoric-dev#validator-1-bld-program)?

@paddyson79 what did you mean by your reply? Are you saying that yes, sending 1 BLD to those wallet addresses would serve decentralization? It looks like we already have a [TC Network create-validator transaction](https://agoric.bigdipper.live/transactions/8E0712A561CF4BB634B4BE109468BCE52C244717FBDFF44FD2CC193BB02046CB) . Did they already get 1 BLD somehow?

**Comment by jeetraut** [comment]
@dckc Correct, these two were collected from the Knack form.

**Comment by dckc** [comment]
We have a discord channel for coordination: [#validator-1-bld](https://discord.com/channels/585576150827532298/946137891023777802).

**Comment by paddyson79** [comment]
> @jeetraut where did that info about TC Network, NodeStake.top come from? Did you get those from [the knack form](https://validateagoric.knack.com/agoric-dev#validator-1-bld-program)?
> 
> 
> 
> @paddyson79 what did you mean by your reply? Are you saying that yes, sending 1 BLD to those wallet addresses would serve decentralization? It looks like we already have a [TC Network create-validator transaction](https://agoric.bigdipper.live/transactions/8E0712A561CF4BB634B4BE109468BCE52C244717FBDFF44FD2CC193BB02046CB) . Did they already get 1 BLD somehow?
> 
> 

Yeah sorry about the confusion. TC network has created their validator as you mentioned, so they shouldn't receive more BLD. Don't know where they got it from.

**Comment by dckc** [comment]
this just in: never mind the multi-sig idea. Please just prepare a list of vetted addresses where Agoric should send 1 BLD.

**Comment by dckc** [comment]
On Jan 28, Agoric announced a [Validator Delegation Program](https://agoric.com/blog/announcements/agoric-validator-program/), where validators would be selected both on the basis of their competence and a pledge to support infrastructure and community growth.

The Agoric blockchain is increasingly decentralized. Anyone can start a node that follows the chain, but in order to get into the market for top 100 validators that participate in consensus, they have to have at least 1 BLD so they can execute a `create-validator` transaction.

Agoric encourages node operators to [Request 1 BLD](https://github.com/Agoric/validator-profiles/wiki/Request-1-BLD). We are grateful to the validators who have agreed to help us review such requests.

`Alan | NodeStake.top` made a [request](https://discord.com/channels/585576150827532298/946137891023777802/947032608947179650) that Agoric send 1 BLD to `agoric1nkhsz0uk0d8qd4p7unrwej0j3ne8acpk447cvf` so that their node, which is running and caught up, can `create-validator` and compete for delegation and a spot in the voting set.

This request was reviewed and approved by two of our reviewers:

 - [KingSuper](https://github.com/aditya-manit/validator-profiles/blob/7a67ad706f1227b74bf14332cdc98c49efab7d7e/KingSuper/README.md)  - [agoricvaloper1fy8r6zq3dde6n7ak6eqy5zsrp3s7sz833dmv32](https://agoric.bigdipper.live/validators/agoricvaloper1fy8r6zq3dde6n7ak6eqy5zsrp3s7sz833dmv32)
 - [pathrocknetwork](https://github.com/Agoric/validator-profiles/blob/3e6291df7ba31720566abf2d39f0611b09f9f2ec/pathrocknetwork-README.md) - [agoricvaloper1uemhjcameshyrts58p38rkd7vmmfsry4z4xn3m](https://agoric.bigdipper.live/validators/agoricvaloper1uemhjcameshyrts58p38rkd7vmmfsry4z4xn3m)

_stay tuned for the next step..._

**Comment by dckc** [comment]
FYI... progress on a relevant bot:

https://github.com/Agoric/testnet-notes/blob/1bld-bot/subm/src/request1bld.js
a61de7c test(request1bld): find endorsements on recent relevant messages

**Comment by dckc** [comment]
Now that liquid BLD is result available from staking rewards and exchange listings, this program is no longer necessary.
